name: hires
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  dotted_border: ^2.0.0
  easy_localization: ^3.0.0
  country_list_pick: ^1.0.1+5
  timelines: ^0.1.0
  flutter_switch: ^0.3.2
  status_change: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  percent_indicator:  
  flutter_zoom_drawer: ^3.0.2
  shared_preferences:
  provider:
  toast:
  fluttertoast: ^8.0.2
  flutter_datetime_picker:
  image_picker:
  get_storage:
  flutter_picker:
  file_picker: ^5.2.2
  flutter_html: ^2.2.1
  dio: ^4.0.6
  multi_select_flutter:
  country_pickers: ^2.0.0
  webview_flutter: ^2.0.4
  url_launcher: ^6.1.6
  share_plus: ^6.3.0
  google_maps_flutter: ^2.2.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/whitejob.jpg"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
